#!/bin/bash

# Environment Setup Script for Vercel Deployment
echo "Setting up environment variables for Vercel deployment..."

echo ""
echo "Required Environment Variables:"
echo "================================"
echo ""
echo "Authentication:"
echo "- NEXTAUTH_URL=https://your-domain.vercel.app"
echo "- NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo "- GOOGLE_CLIENT_ID=your-google-client-id"
echo "- GOOGLE_CLIENT_SECRET=your-google-client-secret"
echo ""
echo "Stock Data APIs:"
echo "- RAPIDAPI_KEY=your-rapidapi-key"
echo "- RAPIDAPI_HOST=apidojo-yahoo-finance-v1.p.rapidapi.com"
echo "- ALPACA_API=your-alpaca-api-key"
echo "- ALPACA_SECRET=your-alpaca-secret"
echo "- ALPACA_URL=https://data.alpaca.markets"
echo ""
echo "Instructions:"
echo "1. Go to your Vercel dashboard"
echo "2. Select your project"
echo "3. Go to Settings > Environment Variables"
echo "4. Add each variable above with the appropriate values"
echo "5. Redeploy your application"
echo ""
echo "For Google OAuth setup:"
echo "1. Go to https://console.cloud.google.com/"
echo "2. Create OAuth 2.0 credentials"
echo "3. Add authorized redirect URI: https://your-domain.vercel.app/api/auth/callback/google"
