name: Backend CI Pipeline

on:
  push:
    paths:
      - "backend/**"
    branches: [master, dev]
  pull_request:
    paths:
      - "backend/**"
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # adjust to your version
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Build binary
        run: go build -o app ./cmd/server

       