name: Backend CI Pipeline

on:
  push:
    paths:
      - "backend/**"
    branches: [master, dev]
  pull_request:
    paths:
      - "backend/**"
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # adjust to your version
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v
        env:
          DB_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/testdb?sslmode=disable
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Build binary
        run: go build -o app ./cmd/server

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gin-backend:${{ github.sha }} .
        working-directory: backend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gin-backend:${{ github.sha }}
